// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiFsnWnItL0JeshPrhB4ymxz5Xl0IYuoY',
    appId: '1:682471459218:android:d83da5ecbdc9547a02994b',
    messagingSenderId: '682471459218',
    projectId: 'tuni-c0211',
    storageBucket: 'tuni-c0211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC_WDapJeA6Mo9nOWwWsS-QBWj9Cnv1fY',
    appId: '1:682471459218:ios:d326271ed253432902994b',
    messagingSenderId: '682471459218',
    projectId: 'tuni-c0211',
    databaseURL: 'https://tuni-c0211-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tuni-c0211.appspot.com',
    iosClientId: '682471459218-6rrhjekl4i7smqg2p5gv3vh9jfei515q.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuni',
  );

}